#!/bin/bash

set -u

BEFORE=`date +%s.%N`
OUT=` dbus-send --system --dest=org.openattic.systemd --print-reply=literal / org.openattic.systemd.ping 2>/dev/null`
AFTER=`date +%s.%N`

MILLIS=`bc <<< "$AFTER - $BEFORE"`

if [ "$OUT" = "   pong" ]; then
    echo "Systemd responded to DBus ping.|time=${MILLIS}s"
    exit 0
else
    echo "Systemd did not respond to DBus ping."
    exit 2
fi
