#!/usr/bin/python
# -*- coding: utf-8 -*-
# kate: space-indent on; indent-width 4; replace-tabs on;
#
#  Copyright (C) 2011-2012, it-novum GmbH <community@open-attic.org>
#
#  openATTIC is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; version 2.
#
#  This package is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
### BEGIN INIT INFO
# Provides: openattic_mounts
# Required-Start: $local_fs $network $remote_fs openattic_LogicalVolume
# Required-Stop: $local_fs $network $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Mount openATTIC's volumes
# Description: Mounts and unmounts volumes for clustering
### END INIT INFO

import sys
import os

if len(sys.argv) != 2:
    print ( "%s <command>\n"
            "\n"
            "Valid commands:\n"
            " * start:   Mount all volumes\n"
            " * stop:    Unmount all volumes\n"
            " * status:  See if any volumes are currently mounted\n"
            " * restart: Umount, then mount all volumes\n" ) % sys.argv[0]
    sys.exit(1)


basedir = dict([
    line.strip().split("=") for line in open("/etc/default/openattic", "rb") if line.strip()
    ])["OADIR"].replace('"', '')

sys.path.append( basedir )
os.environ['DJANGO_SETTINGS_MODULE'] = 'settings'

from lvm.models import LogicalVolume

command = sys.argv[-1]

if command == "start":
    print "Mounting all volumes..."
    LogicalVolume.mount_all()

elif command == "stop":
    print "Unmounting all volumes..."
    LogicalVolume.unmount_all()

elif command == "restart":
    print "Unmounting all volumes..."
    LogicalVolume.unmount_all()
    print "Mounting all volumes..."
    LogicalVolume.mount_all()

elif command == "status":
    mounted  = LogicalVolume.mounted_volumes()
    volcount = LogicalVolume.objects.exclude(filesystem="").count()
    if mounted:
        print "There are currently %d mounted volumes (%d total)." % (len(mounted), volcount)
        sys.exit(0)
    else:
        print "There are currently no mounted volumes (%d total)." % volcount
        sys.exit(3)

elif command == "probe":
    print "restart"

else:
    print "Unknown command %s." % command
    sys.exit(1)
