#!/bin/bash
#
#  Copyright (C) 2011-2015, it-novum GmbH <community@openattic.org>
#
#  openATTIC is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; version 2.
#
#  This package is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

### BEGIN INIT INFO
# Provides: openattic_rpcd
# Required-Start: $local_fs $network $remote_fs postgresql openattic_systemd
# Required-Stop: $local_fs $network $remote_fs postgresql
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: openATTIC's XMLRPC interface daemon
# Description: handles communication with other hosts
### END INIT INFO



set -e
set -u

i=0

if [ -f /etc/default/openattic ]; then
	. /etc/default/openattic
else
	echo "Missing required file /etc/default/openattic."
	exit 1
fi

if [ $# -lt 1 ]
then
	echo "$0 <start|stop|restart|status>"
	exit 1
fi

. /lib/lsb/init-functions

function mklogfile() {
	if [ ! -z "$1" -a ! -e "$1" ]; then
		touch "$1"
		chown "$RPCD_CHUID" "$1"
	fi
}

case $1 in
	start)
		if [ -e /var/lib/openattic/database-unconfigured ]; then
			echo "not starting openATTIC rpcd: the database has not been configured. run oaconfig install."
			exit 0
		fi
		log_daemon_msg "Starting" "openATTIC rpcd"
		if [ ! -z "$RPCD_CERTFILE" -a ! -z "$RPCD_KEYFILE" ]; then
			RPCD_OPTIONS="$RPCD_OPTIONS -c $RPCD_CERTFILE -k $RPCD_KEYFILE"
		fi
		mklogfile "$RPCD_LOGFILE"
		shift
		env - PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
			start-stop-daemon --pidfile=$RPCD_PIDFILE --make-pidfile --background --oknodo --start \
			--exec $PYTHON --chdir $OADIR --chuid $RPCD_CHUID -- \
			$RPCD_OPTIONS -l $RPCD_LOGFILE "$@"
		while ! start-stop-daemon --pidfile=$RPCD_PIDFILE --test --stop --exec $PYTHON --quiet; do
			sleep .1
			if [ $i -ge 100 ]; then
				log_failure_msg "openattic_rpcd start failed"
				log_end_msg 1
				exit 1
			else
				i=$(( i + 1 ))
			fi
		done
		log_end_msg 0
		;;
	
	foreground|fg)
		if start-stop-daemon --pidfile=$RPCD_PIDFILE --test --stop --exec $PYTHON --quiet
		then
			PID=`cat $RPCD_PIDFILE`
			echo "rpcd is already running (pid $PID), please stop it first."
			exit 0
		else
			cd $OADIR
			shift
			su ${RPCD_CHUID%%:*} -- -c "$PYTHON $RPCD_OPTIONS"
		fi
		;;
	
	profile)
		if [ -z "`which pyprof2calltree`" ]; then
			echo "This command requires pyprof2calltree. You can install it using easy_install pyprof2calltree."
			exit 1
		fi
		
		$0 stop
		
		mkdir -p /tmp/profile_data
		mkdir -p /tmp/profile_kcachegrind
		chown -R ${RPCD_CHUID%%:*} /tmp/profile_data
		
		$0 start --profile
		
		echo "Converting files for kcachegrind..."
		cd /tmp/profile_data
		while sleep 1; do
			for profile in *.profile; do
				[ -f "$profile" ] || continue
				converted="/tmp/profile_kcachegrind/$profile"
				if [ ! -e "$converted" ]; then
					echo "$profile"
					pyprof2calltree -i "$profile" -o "$converted"
				fi
			done
		done
		;;
	
	stop)
		log_daemon_msg "Stopping" "openATTIC rpcd"
		env - PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
			start-stop-daemon --pidfile=$RPCD_PIDFILE --stop --oknodo --exec $PYTHON
		while start-stop-daemon --pidfile=$RPCD_PIDFILE --test --stop --exec $PYTHON --quiet; do
			sleep .1
			if [ $i -ge 100 ]; then
				log_failure_msg "openattic_rpcd stop failed"
				log_end_msg 1
				exit 1
			else
				i=$(( i + 1 ))
			fi
		done
		log_end_msg 0
		;;
	
	restart|reload|force-reload)
		$0 stop
		$0 start
		;;
	
	status)
		if start-stop-daemon --pidfile=$RPCD_PIDFILE --test --stop --exec $PYTHON --quiet
		then
			PID=`cat $RPCD_PIDFILE`
			echo "rpcd is running (pid $PID)."
			exit 0
		else
			echo "rpcd is not running"
			exit 3
		fi
		;;
	
	probe)
		echo restart
		exit 0
		;;
	
	*)
		echo "Unknown command $1."
		exit 1
		;;
esac

